# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3782fd5d33f409df0206b5ac5596429449c44742d4724383d14a7e2485729fa3a134cf97d928a967a38ca7ddda2db80d1e4f0695847c1dcf7df038e5a8c017c

test:
  secret_key_base: dd9d9295cb06f26dffd4599c1efa96ea6cff9448e26d8f04b41cb119cdf3b2c083dc1ca04670b6465ee4422a3798ab8df970fd73c96827ad7f450bd23ae6f245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
